grails:
    profile: rest-api
    codegen:
        defaultPackage: uk.ac.jisc.monitorlocal
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

server:
    contextPath: /monitorLocalSvc
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents: []
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
          maxFileSize: 20971520
          maxRequestSize: 23068672
    converters:
        encoding: UTF-8
        default:
          circular:
            reference:
              behaviour: DEFAULT
        json:
          default:
            deep: true
    databinding:
      enableSpringEventAdapter: true
      dateFormats:
        - "yyyy-MM-dd'T'HH:mm:ssZ"
        - "yyyy-MM-dd'T'HH:mm:ss.S'Z'"
        - "yyyy-MM-dd'T'HH:mm:ss'Z'"
        - "yyyy-MM-dd'T'HH:mm'Z'"
        - 'yyyy-MM-dd HH:mm:ss.S'
        - 'dd/MM/yyyy'
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

environments:
    development:
       dataSource:
            dbCreate: update
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5Dialect
            username: k-int
            password: k-int
            url: jdbc:mysql://localhost/MonitorLocalDev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
            pooled: true
            # logSql: true
            properties:
              maxActive: -1
              minEvictableIdleTimeMillis: 1800000
              timeBetweenEvictionRunsMillis: 1800000
              numTestsPerEvictionRun: 3
              testOnBorrow: true
              testWhileIdle: true
              testOnReturn: true
              validationQuery: select 1
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---    
grails:
  plugin:
    springsecurity:
      basic:
        realmName : "Jisc Monitor"
      useBasicAuth: true
      userLookup:
        userDomainClassName: 'uk.ac.jisc.monitorlocal.User'
        authorityJoinClassName: 'uk.ac.jisc.monitorlocal.UserRole'
      providerNames:
        - 'preAuthenticatedAuthenticationProvider'
        - 'daoAuthenticationProvider'
      authority:
        className: 'uk.ac.jisc.monitorlocal.Role'
      controllerAnnotations:
        #
        # N.B. Static Rules need to be the name of the controller, not the mapped URL - so /aoGrant/** and NOT /grant/** or you'll get a 403.
        #
        staticRules:
          -
            pattern: '/jwt/**'
            access:
              -
                'permitAll'
          -
            pattern: '/ghHelp/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/application/**'
            access:
              -
                'permitAll'
          -
            pattern: '/angularHelper/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/ref/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/budget/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/internalApi/**'
            access:
              -
                'ROLE_SYSTEM'
          -
            pattern: '/person/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/invoice/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/ao/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/org/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/grant/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/aoGrant/**'
            access:
              -
                'ROLE_USER'
          -
            pattern: '/academicOutput/**'
            access:
              -
                'ROLE_USER'
        chainMap:
          -
            # Register /internalApi as using basic auth -- ONLY for usage when triggering local scripts etc
            pattern: '/internalApi/**'
            filters: 'JOINED_FILTERS,-exceptionTranslationFilter,-jwtPreauthFilter'
          -
            pattern: '/assets/**'
            filters: 'none'
          -
            pattern: '/**/js/**'
            filters: 'none'
          -
            pattern: '/**/css/**'
            filters: 'none'
          -
            pattern: '/**/images/**'
            filters: 'none'
          -
            pattern: '/**/favicon.ico'
            filters: 'none'
          -
            pattern: '/**'
            filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter,-basicAuthenticationFilter,-basicExceptionTranslationFilter'
---
monitorLocal_jwk:
  kty: "RSA"
  kid: "k1"
  n: "oYfKNEfsrDdi8hEFPL8CQ0CKS3XiugjST_i3D1d7FiNjCY9hyj4qEuLmm7PGF93yiccny6bWr37shzun59jXOf62zFwFK_HeBpWKSz2QTWCVjfqrfgQYOYDzqHZnAEwlcueswaYx83HIUzBCigr4kAphwDpPMixveSj4n3PxCCEza6Qycp3KdhHq4JUfqzd0lFtm2EGBnqKkOiVCy1oRGJaHjhDb_oHgNs1eKmqVuuKl-OsUbmnMP4HOEVCH1y8D4JLEzPzrE0CZcip5e1nm2qGlOnW-vL7l-rGoxSn47rAsX408uNTafhI4SdD3CSeeEvS7OnSNN1whTYBIbFN9vw"
  e: "AQAB"
  d: "Xd8SDYv26KZPZCmsB39hiz_Ins3lcwOJZVw-1jWanGT4OygORoAV51_hcH7rEhezyYnpgJp2jQqP3o82prAHc_aouN6JSt6GjwD8m3ktkSod_6K7YsJyaYidETut5ChcYwhsByXURYvMRTv4j0yM4viFkjbQq3HTXnAG_HNekb_4vLUmHc7VXGs1OK0532V7wJAXrdC6SOvSHPSXSvSAF7HgNYrMvQ1P1abGcypXabURO5jEt_qd02tEFMheyrkyZ_wjTbOCYdPX-w6x3GbHhF1hyQ9F0jtgLCRTWTIo4TIxIlwJppHlDaLzuUmd0FZstDfCwqiGX4JSeAWUhYSm0Q"
  p: "93DT9AgQX1M87J_OTmr9AGfDz5TnxEkwLu7Ufi6YPpaCQ8DGbeVVUYRmL3fEYOFJA22bROPd4DQndL75W-rxRaYB95jBT4jQervzllSkbyd5OR9PBGN7plLrlPzY0gnPNMtQAjoP0rQ6J5pWjQNQ5LMm5eELyeTddnveSrLWrq0"
  q: "px4yZqU9Qw2kQBXgTVdoqfy8NWx1Ea3c2skc4BfphtI91QGorcsitgMO-wJII9t-DnZTqrOexVPYV65lnMxrysbeiQjKzfv93fMUuMi8dWgjcoCIgh5tS-RYgTNNQLyAYAQbKcf4pEH5EpsyXUP1XiTaKvCOfcQ_OonYbsL1B5s"
  dp: "cJpn2iXRTZATqZsPx5_ogsa11UFuN2UXCESnbsTFg7X6kdqoclpq-S3HUtKuC2h6UZUPk8oermkNi5Nc5veD1K43NvXNAuS_-xqNP1xFeE_-WoBk9RpQquARVTu7b9oG8X-UaW8CxGBAFsWlnYZkya69hN9k_fuozMKR5mx8RgE"
  dq: "ZM2fIzEqucaBu7I2YRCHbnmnYSYxm19fJ41F4Jor34nziAd_Io20O0uu_pNKxm5AJCMVppLAA1Dm30SvwBvCLUc1tjzab9M_N2DHsApNOxh8wTVsoegOj0eGZzB1ucW6PbBcXiBkB1hQD_wTLhSu7YGXI22E1bHJXdsF9RGd0V8"
  qi: "gqDj9Pfl9IhLAVn00a3RYZsxiODyySqEfpVkgHkHai0Mq1-5oC0dhWYr9IXjCX7RMjTzHhgSXxb7eR4EjqvyCboH1m904m5_myPi5wxBYWaGnr9wQ8CZ1TosU9PtBHz_UlRY2xPCTYY-kqEd1JDUx0GqwEP06mJW2DcNBL9nLyo"
  
auth:
  sob:
    key: 'monitorLocalDev'
    secret: 'monitorLocalDevSecret'
    scope: 
      - 'read'
    defaultRoles:
      - 'ROLE_USER'
      - 'ROLE_GOOGLE'
    accessTokenUrl: 'https://demo.kbplus.ac.uk/sobtest/oauth/token'
    peopleApiUrl: 'https://demo.kbplus.ac.uk/sobtest/userinfo'
    query: {}
    userMapping:
      username: "sub"
      name: "name"
      profilePic: "picture"
      email: "email"
      
  google:
    key: '186678964269-tajnf5mojsdsa4mk66846apd0d0adc9q.apps.googleusercontent.com'
    secret: 'yu28ndRVECEqQ1_PHpwddr0h'
    scope: ''
    defaultRoles:
      - 'ROLE_USER'
      - 'ROLE_GOOGLE'
    accessTokenUrl: 'https://accounts.google.com/o/oauth2/token'
    peopleApiUrl: 'https://www.googleapis.com/oauth2/v3/userinfo'
    query: {}
    userMapping:
      username: "sub"
      name: "name"
      profilePic: "picture"
      email: "email"

---
elasticSearch:
  datastoreImpl: hibernateDatastore
  bulkIndexOnStartup: true
  cluster:
    name: elasticsearch
  index:
    name: monitor-local
  migration:
    strategy: delete
  date:
    formats: 
      - "yyyy-MM-dd'T'HH:mm:ss'Z'"
  defaultExcludedProperties:
    - password
  client:
    mode: transport
    hosts:
      -
        host: localhost
        port: 9300
---
k_int:
  grails:
    tools:
      rules:
        compliance-rcuk: 'uk.ac.jisc.monitorlocal.rules.ComplianceRCUK'
        workflow: 'uk.ac.jisc.monitorlocal.rules.Workflow'
      finance:
        currencies:
          - EUR
          - USD
          - GBP
          - CHF
        defaultCurrency: GBP
        exchange:
          yahoo:
            host: 'http://query.yahooapis.com'
            uri: '/v1/public/yql'
            paramYql: q
            paramOther:
              format: json
              env: 'store://datatables.org/alltableswithkeys'
---
monitor:
    helpHost : 'https://github.com'
    helpUri     : '/k-int/MonitorLocalUX/wiki'
